### ISSUE TITLE
setup and run fallback-studio as a standard user

### ISSUE THREAD

**Issue by shathish-vsk** [Jordaneisenburger/fallback-studio#11]
I work in a controlled environment on Ubuntu 18.04. I have a standard user account (not a sudo user), my companies security policies would not allow me to have sudo permissions. How am I supposed to watch the environment once built.

when I try to run
yarn run watch:example-shop,

I'm prompted for sudo password for my username. I don't see a reason for a sudo operation to open up a storefront on a particular port. pwa-studio runs (I can watch venia storefront) without me being a sudo user.

Is there a way to bypass the sudo privilege, as it is a tedious process to raise a support ticket to my administrator every time when I try to spin up the project.

**Comment by Jordaneisenburger** [comment]
Hi @shathish-vsk, Thanks for the question. I will need to check why this happens I'll get back to you.

**Comment by Jordaneisenburger** [comment]
@shathish-vsk does this issue still persist ?
