### ISSUE TITLE
ProductImage must have a sub selection

### ISSUE THREAD

**Issue by Huaoe** [Jordaneisenburger/fallback-studio#2]
browsing : https://fallback-studio-example-shop-amwsw.local.pwadev:8415/venia-dresses.html

<pre>UpwardServerError: Request did not evaluate to a valid response, because: <br>Error: Error: Field &quot;small_image&quot; of type &quot;ProductImage&quot; must have a sub selection.<br> &nbsp; &nbsp;at makePromise.then (C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback-studio\src\example-company\example-shop\node_modules\@magento\pwa-buildpack\node_modules\@magento\upward-js\lib\resolvers\ServiceResolver.js:83:27)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:68:7)<br> &nbsp; &nbsp;at buildResponse (C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback-studio\src\example-company\example-shop\node_modules\@magento\pwa-buildpack\node_modules\@magento\upward-js\lib\buildResponse.js:30:15)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:68:7)<br> &nbsp; &nbsp;at UpwardPlugin.&lt;anonymous&gt; (C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback-studio\src\example-company\example-shop\node_modules\@magento\pwa-buildpack\node_modules\@magento\upward-js\lib\middleware.js:72:21)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:68:7)</pre>
</body>
</html>

**Comment by Huaoe** [comment]
Well, I've tested working with a mac and it wokrs like a charm...

**Comment by amitmaurya1024** [comment]
add the following in product query 

```
{...
small_image{
    url
}
....
}
```
