### ISSUE TITLE
ERROR in ./FETCH_ROOT_COMPONENT

### ISSUE THREAD

**Issue by Huaoe** [Jordaneisenburger/fallback-studio#3]
Hello,

on a windows port I have this error popping up 
I think it's a path building issue because we can see this string 

....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js'
otherwise
FETCH_ROOT_COMPONENT refer to MagentoRouteHandler
but I don't understand the mecanism yet.

any clue would be likely,

Thomas

`
ERROR in ./FETCH_ROOT_COMPONENT
Module not found: Error: Can't resolve '....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js' in 'C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop'
resolve '....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js' in 'C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop'
  Parsed request is a module
  using description file: C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\package.json (relative path: .)
    resolve as module
      looking for modules in C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop
        using description file: C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\package.json (relative path: .)
          using description file: C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\package.json (relative path: ./....pwa-studiopackagesenia-conceptsrcRootComponentsCMSinde
x.js)
            no extension
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js doesn't exist
            .mjs
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.mjs doesn't exist
            .js
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.js doesn't exist
            .json
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.json doesn't exist
            .graphql
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.graphql doesn't exist
            as directory
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js doesn't exist
      C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\node_modules doesn't exist or is not a directory
      C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\node_modules doesn't exist or is not a directory
      C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\node_modules doesn't exist or is not a directory
      C:\Users\Thomas\Documents\_Projects\Magento\node_modules doesn't exist or is not a directory
      C:\Users\Thomas\Documents\_Projects\node_modules doesn't exist or is not a directory
      C:\Users\Thomas\Documents\node_modules doesn't exist or is not a directory
      C:\Users\Thomas\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules
        using description file: C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\package.json (relative path: ./node_modules/....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules
        using description file: C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\package.json (relative path: ./node_modules)
          using description file: C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\package.json (relative path: ./node_modules/....pwa-studiopackagesenia-conceptsrcRootComp
onentsCMSindex.js)
            no extension
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js doesn't exist
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
            .mjs
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.mjs doesn't exist
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
            .js
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.js doesn't exist
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
            .json
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.json doesn't exist
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.json doesn't exist
            .graphql
              Field 'browser' doesn't contain a valid alias configuration
            .graphql
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.graphql doesn't exist
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.graphql doesn't exist
            as directory
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js doesn't exist
            as directory
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js doesn't exist
      looking for modules in C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept
        using description file: C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\package.json (relative path: .)
          using description file: C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\package.json (relative path: ./....pwa-studiopackagesenia-conceptsrcRootComponentsCM
Sindex.js)
            no extension
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js doesn't exist
            .mjs
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.mjs doesn't exist
            .js
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.js doesn't exist
            .json
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.json doesn't exist
            .graphql
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.graphql doesn't exist
            as directory
              C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js doesn't exist
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.mjs]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.js]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.json]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.graphql]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\node_modules]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\node_modules]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\node_modules]
[C:\Users\Thomas\Documents\_Projects\Magento\node_modules]
[C:\Users\Thomas\Documents\_Projects\node_modules]
[C:\Users\Thomas\Documents\node_modules]
[C:\Users\Thomas\node_modules]
[C:\Users\node_modules]
[C:\node_modules]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.mjs]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.mjs]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.js]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.js]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.json]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.json]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\example-company\example-shop\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.graphql]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\node_modules\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.graphql]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.mjs]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.js]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.json]
[C:\Users\Thomas\Documents\_Projects\Magento\FallBackStudio\fallback2\src\pwa-studio\packages\venia-concept\....pwa-studiopackagesenia-conceptsrcRootComponentsCMSindex.js.graphql]
 @ ./FETCH_ROOT_COMPONENT 3:32-164
 @ C:/Users/Thomas/Documents/_Projects/Magento/FallBackStudio/fallback2/src/pwa-studio/packages/peregrine/dist/Router/MagentoRouteHandler.js
 @ C:/Users/Thomas/Documents/_Projects/Magento/FallBackStudio/fallback2/src/pwa-studio/packages/peregrine/dist/Router/index.js
 @ C:/Users/Thomas/Documents/_Projects/Magento/FallBackStudio/fallback2/src/pwa-studio/packages/peregrine/dist/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?https://fallback-studio-example-shop-8kix8.local.pwadev:8464 (webpack)/hot/dev-server.js ./src/index.js
`

**Comment by Huaoe** [comment]
Hi,
got some news about this error.
so what shortly I did is to use the pwa-studio (fix/windows_dev_experience) branch
I've yarn add cross-env (eventually cross-var but not required as the last change is solving related issues)

and changed : "watch:example-shop": "yarn workspace @fallback-studio/example-shop run watch"

cheers

**Comment by Jordaneisenburger** [comment]
Awesome! Not sure in what file you changed `watch:example-shop": "yarn workspace @fallback-studio/example-shop run watch` i guess you didn't change this inside fallback-studio repo  or did you ?

**Comment by Jordaneisenburger** [comment]
Sure im curious to see what you exactly changed, if you could do a PR that would be nice!
