### ISSUE TITLE
Unable to update logo image

### ISSUE THREAD

**Issue by jaimin-ktpl** [Jordaneisenburger/fallback-studio#5]
Not able to update logo image using the fallback theme.

### Steps to reproduce:

1. Go to src/components, create a new directory with name Logo
2. Go to venia-concept/src/components/Logo and copy index.js and logo.js files to your Logo directory.
3. Add your custom logo.svg file in your Logo directory
4. `execute yarn cache clean`
5. `execute yarn run clean:example-shop`
6. `execute yarn run watch:example-shop`

### Expected result:
Front app should display new logo

### Actual Result:
Front app logo is still the same coming from venia-concept

**Comment by jaimin-ktpl** [comment]
I got to figure out the issue. It was my mistake in understanding the fallback mechanism. I did not change Header component. Once I added Header component and updated main.js to include my custom Header component, it was working correctly.

**Comment by Jordaneisenburger** [comment]
Hi Jaimin,

No worries, sometimes it can get a little tricky indeed. Good to see you figured it out!
