### ISSUE TITLE
When the sample storefront component footer is modified, the page is not loaded.

### ISSUE THREAD

**Issue by threescs** [Jordaneisenburger/fallback-studio#6]
Unable to reach the page hot update, causing the page to report an error, as shown in the figure

![image](https://user-images.githubusercontent.com/29721759/57981539-45a45e00-7a6b-11e9-8f04-96ecae11422b.png)
![image](https://user-images.githubusercontent.com/29721759/57981540-489f4e80-7a6b-11e9-9334-88b9df38eb45.png)

**Comment by threescs** [comment]
![image](https://user-images.githubusercontent.com/29721759/57981564-8dc38080-7a6b-11e9-81ff-7d71549798a7.png)

**Comment by threescs** [comment]
It seems that the file of dist was not found after webpack was packaged.

**Comment by Jordaneisenburger** [comment]
Hi @threescs does this  issue still occur, if so pleas let me know how to reproduce.

**Comment by threescs** [comment]
> Hi @threescs does this issue still occur, if so pleas let me know how to reproduce.

Thank you, solved
